"""added bio and status column to user model

Revision ID: 245547093a73
Revises: fb40d61a0062
Create Date: 2024-04-27 14:39:37.253747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245547093a73'
down_revision = 'fb40d61a0062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
