"""added Want and Pass models

Revision ID: b1a2a5253ed1
Revises: 381ebc72cd34
Create Date: 2024-03-20 11:04:01.126304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a2a5253ed1'
down_revision = '381ebc72cd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_passes_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_passes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passes'))
    )
    op.create_table('wants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_wants_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wants_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wants'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('endorse')
        batch_op.drop_column('renounce')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renounce', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('endorse', sa.INTEGER(), nullable=False))

    op.drop_table('wants')
    op.drop_table('passes')
    # ### end Alembic commands ###
