"""changed Post.pic_content to pics and to be a relationship with new Pic model

Revision ID: fb40d61a0062
Revises: de3c0d8d1863
Create Date: 2024-04-24 21:38:50.899859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb40d61a0062'
down_revision = 'de3c0d8d1863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_pics_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pics'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('pic_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_content', sa.VARCHAR(), nullable=True))

    op.drop_table('pics')
    # ### end Alembic commands ###
